services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - fastapi_data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - backend
    restart: always
    
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      ollama: 
        condition: service_started
    env_file:
      - ./env/.env.app



  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=medical_files
    networks:
      - backend
    restart: always 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_THREADS=4
      - OLLAMA_NUM_PARALLEL=2         
      - OLLAMA_MAX_LOADED_MODELS=3
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - backend
    restart: always
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ollama serve &
        
        until ollama list >/dev/null 2>&1; do 
          sleep 1
        done
        
        echo "=== Pulling llama3.2:3b ==="
        ollama pull llama3.2:3b
        
        echo "=== Pulling medgemma:4b ==="
        ollama pull medgemma:4b

        echo "=== Pulling mxbai-embed-large ==="
        ollama pull mxbai-embed-large

        wait
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 10s       
      timeout: 5s       
      retries: 60       
      start_period: 10s 

networks:
  backend:

volumes:
  fastapi_data:
  postgres_data:
  qdrant_data:
  ollama_data: