APP_VERSION=1

Max_SIZE_FILE=50
FILE_ALLOWED_TYPES=["text/plain","application/pdf"]
CHUNK_SIZE=512
OVERLAP_SIZE=200



POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="password"
POSTGRES_HOST="postgres"
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE="medical_files" 

LLAMA_CLOUD_API_KEY="llx-qBH9YGerMEBfVqPHgVrpwJQ3UVGXZ4Dji5XKdwudFzGXsVUU"


DEFAULT_LAN="en"
PRIMARY_LAN="en"


OPENAI_KEY="vbgntymyu"
OPENAI_URL="http://ollama:11434/v1"
OLLAMA_URL="http://ollama:11434"


CHAT_MODEL_ID="qwen3.5:4b"
GENERATION_MODEL_ID="qwen3.5:4b"
EMBEDDING_MODEL_ID= "mxbai-embed-large"
EMBEDDING_MODEL_SIZE=1024


INPUT_DEFAULT_MAX_CHARACTERS=1024
GENERATION_DEFAULT_MAX_TOKENS=200
GENERATION_DEFAULT_TEMPERATURE=1.0
AGENT_TEMPERATURE=0.1


QDRANT_DB_PATH="http://qdrant:6333"
QDRANT_DB_METHOD="Cosine"
QDRANT_COLLECTION_NAME="medical_chunks"

TAVILY_KEY="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"