APP_VERSION=1

Max_SIZE_FILE=50
FILE_ALLOWED_TYPES=["text/plain","application/pdf"]
CHUNK_SIZE=512
OVERLAP_SIZE=200



POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="password"
POSTGRES_HOST="postgres"
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE="medical_files" 

LLAMA_CLOUD_API_KEY="llx-qBH9YGerMEBfVqPHgVrpwJQ3UVGXZ4Dji5XKdwudFzGXsVUU"


DEFAULT_LAN="en"
PRIMARY_LAN="en"


GROQ_KEY="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"
GROQ_URL="https://api.groq.com/openai/v1"
JINA_KEY="jina_aed9606016424b268c87ab64d8f8e7e6adcThJhvp7M1sfekDQMFb6cWnBMf"
JINA_URL="https://api.jina.ai/v1"


CHAT_MODEL_ID="openai/gpt-oss-20b"
GENERATION_MODEL_ID="openai/gpt-oss-20b"
EMBEDDING_MODEL_ID="jina-embeddings-v3"
EMBEDDING_MODEL_SIZE=1024


INPUT_DEFAULT_MAX_CHARACTERS=4096
GENERATION_DEFAULT_MAX_TOKENS=1024
GENERATION_DEFAULT_TEMPERATURE=1.0
AGENT_TEMPERATURE=0.1


QDRANT_DB_PATH="http://qdrant:6333"
QDRANT_DB_METHOD="Cosine"
QDRANT_COLLECTION_NAME="medical_chunks"

TAVILY_KEY="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"

LANGSMITH_TRACING_V2="true"
LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY="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"
LANGSMITH_PROJECT="medical knowledge assistant"